### ISSUE TITLE
Argument error when trying to create new boolean

### ISSUE THREAD

**Issue by neybar** [navsmb/devops-skill-challenge#2]
After fetching the latest changes I'm getting the following error on this page (http://localhost:8080/boolios):

```
Started POST "/boolios" for 172.17.0.1 at 2018-05-15 23:54:04 +0000
Processing by BooliosController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"{{ token replaced }}", "boolio"=>{"val"=>"1"}, "commit"=>"Save"}
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.3ms)

ArgumentError (bad argument (expected URI object or URI string)):
  app/models/boolio.rb:33:in `create_baas'
  app/controllers/boolios_controller.rb:55:in `block in create'
  app/controllers/boolios_controller.rb:54:in `create'
```

**Comment by neybar** [comment]
Looks like the App changed.  README FTW.

**Comment by neybar** [comment]
Although it begs the question, what is `BOOL_API_URL` supposed to be?  Is there a default value that this should be?

**Comment by stmpy** [comment]
Yes, sorry http://boolio.nav.engineering/booleans/
